apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quizup-prod
resources:
  - manifests.yml
  - sealed-secret.yml
images:
  - name: ghcr.io/quizup-organization/social
    newTag: "1.0.0"
