---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-social-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_PASSWORD: AgCRKCMYbX+3jSWNaZIqOXkBGXrsTr9gf4MhKSPL45CwQWCTJbPFvwInBEi61uCNOLIPkPfkSoY50T9FC31L4rrhXGqKwGpBLkomIjwWw0qwfS0XCS5rtUL4NNwtjrjr0XpQCl7O7uKePRCtPUXOI7v0iBImRDclLVZA2Js/F8zCBbNXju72Sm9cL0Nve5LK1hVksC2PHe/2vzEv4dLBcY07iThSdsO9JgyOhT4yHO4Y7EqMFxoJRIPwXBGt416hkvakRC8eQ0O+Yrs+U9v2O9ENsmQCYlY3gvTh3b1m17RCnMLlT0s1DIurMYe8RAVHoLKMtqx5NkdXeTaGbuvUQPuLjO6yU5C1jLJABT66OARIcLGYVN5Ve6sXwulTR/y1AsrPxeP00fS2RJDmWBwkH7wzV/wx4Qvph5Ry6CG+wbw0z489JrzUj2AYgycxBstRJKsI8GO2oaEkdnsPDXOr+mkF5nu5epPUFI1/XZfI01AiJoPh8MFv6KlZ6w+IFsJfcMa9Ofb3yguK9jpNFsI7oMJq8Il2YWJUuHsEQEqRw7fLgqzs0IO+1suraDx1TtkUnTnWMQRDVnatJTYcDK1M/EHFQNEb+DwtlLJ5D3bFqhZrFEVoeo1SUZOIgSJpbQ3R/SxgnR2bAq1hjjGQjjs3YY7tn2pL/jEf57f0D3xUeCjN6JgK5Wz02slHsm3nR/Iqbmkn6mxIY4BCYjGHzBDbX/S3U/QOY61qFiOyGYMOJl1SppaPN4f7stsxM74tbNrw4qI=
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgBOVBHlW+xmkfA3XZKcR5iYSo/DY7kPWqSCY0goEHt4AJaFT9+graWxlFQbGdCPdImt2aOuCnP3X1XnuqqMvUuGZzc78zoWQUjqqAwadNrzbfn6rv9rd8AgNUG7hZAU4MpmGSWwcKk+M9ariz7iu3UEXx1haO4oZODMQ5I08K96Jk17nXxNpT5GZrVOkMBJolufUDsCsA43kXWLx9WFIR6RnJpSBnMBEqLHRBnDWub2X8Z6hztCHPEEAaWCHeMDnFRJucZ1ffTVFK6Vlkj45KWMskUGjOFJS8r0dPaFHOqZcI45Y0bn55Pai8bVfutSgzcg5+diIaBGDobQ+VNoLac0NP8fkftvK61vlIIo8xjmNW8W5R4YP8DpvrGuHPcsgpzh1O+vtCtBmvEeFofXFgjvLwkj+4oxjo9kcplezvRLbYQvvZOYeWMgdk3ivRWZmXtBGYvOzeHnrqJlvKyWSj3B5WOfUk0BEq62/wP1tQrmLU/iikyfcD/QKO6aCeK0jTIgarynhirDBJjD1XL2KHrKxofwfA2WlCC12L+pe88P5BozOZg+P8coVRuZEGbJ7WQupGs7rpxxv/iAjonCtaRl0nYAazlo/lXCJwGWVgce6/txrAFip6uWWZpwd250VpNkMo7cTGFZ2wZE6hHr0q0V+CxCyc+UqUoFoPMWDR10+PHaF9m7xfhIbscERoVQItrwG7Scc9rqeDYPYUlzImG6lauRDUD6RWGRxj06MC7ns2z6FfQiQJgcuZSqrS+rfbQ=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-social-secret
      namespace: quizup-prod
