---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-social-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_PASSWORD: AgBpZo5KeN2XoXZffZQ+AdnnetbZkwWsZ769ZMmzkaqs2hCZnmO5Or2Ppmu2/Q2faqibrJnWfKbbM1kvLzMnppiMSM1/kqwdyzuGotHQsN8SJTWiA2vfpq+Gh2A1AMhb9UoieA38Fnk+usGVRHnSOcToKaO6mUX1NJ61NII8PuDhXp+PA+/pH5AlJCcmkE44WiwIdxDthm7VYKYxYmqsUlRchCkFbRHGvebHAobrJnN/W4a6doh2tvdwG6WsXslBClNjIZ6ddDuzqdpXNxRIc8hAelHZJ24WG5zs9uUPrs2xeHV+QzKOBt9GBcPNh95oE7tN73ifltY8WBDb7BzxUWnSgUoO/70xXi2DTrCw/xZdgoA9yj14ry6CdS38/iC/neRRhRLlWNDGo/5/wfUcuOjh0tTKx9wevhHlijYzKm85TLzpOYni15p1+WLKAM/84Z4bX6kEEvXXNiOlAM1/Cde/Ox4N5mQY9DWNYkZpwyCWLvBgcx/LTSJEQbyS+G2SHAjYcF6D4FvFUNl0PsvQjmtDW/J3YejXE6JrnUO1B5sgyEzyxQACHqHP38IR02EvEFMm855zxMls7DZV+LAvvP4A54NVbxAOOmpnJnOpPj9TMVfB9MeewfavxZy7R6K2XSymRJziKi688shLtFr4QMAgGs9mygxLTFd5y5c6JpT94m4jJgqTPz6dMk3BSzOcahHJs3ykzBWzth/cJdukXq26z4u878M5JptmxgkRybyxGdJa6kdlUi71IhmEe4pBxqY=
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgCK7ArwrRt4pie6kxTPWJ7JeFrHclvDwQKvRjlIPGPGBMptwgLfeVW2Dlupr3StuEq42Ab+fwRClCa0y5BK2EvoijmAFnAaeBjAiKJGOcbQ1vIvkLtBColQRu/I37oHjb5pTAepBJLLG6MHq9bLB8vWkRegPloBUOpT/ce4X5R7Rj9ChT/0cmXzlEblVD+HYkG2NLXkc/jRsJD/m095TdpLErauw8qg2+eWW/PrEshxl4Ry32GKjiQtHv2NxwzZrWhM40W33WlpUcyqy6Kiv3RPd2B/rDofS/v1d/nQnf/4xFbehwv/BvsyAuAbkeyFClDp/hH0Y7NMKEojW+4xPiGxr/KJ5hdXeVUdkJ9v76DeN0VzxPFQtIkt0XPZWd7BpOKxCs/0NHYLmvvGkwT10rhsOmS6kdYoPSzn1aAGp+P2v12Fx3XenIrc6I7/Dphw5VJT1hRiZy+ucjOmuqkCFmySsUIg3P06oJpxQz7JkmNDlw3gFHICPe+D3hZwoEI8VtSI/IvQSaqUuYeCfSpKDBJ/PCSD2niMi6XLl2IvtBgAyXf4kKzaNsitSUzN5HGrTbmw7RziiEFbzrwK3j89cjfZm6y5e2R2lGSO+1zXIbnWtN0uMDkPHcbUgzBy0wHE+F1XdBnYZrf9njTW4ao2kwAfGunkr55haPbWrrSePiptXaL1b/6cZn8cTmpb8/8Lmlrw/r0hyPcH5RxVVVrzSCv2O9wrI+6nnxyJntKmk6gox2K+WPFKMmxtw6z0xHzPpQY=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-social-secret
      namespace: quizup-prod
