---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-matchmaking-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_PASSWORD: AgAHZiGbPvxlf6SibNOJUezZHEYmXHr04/P4uEb04aKM6LiI0T95sCGQqi2O7VgPK0PSphTYYVi+srgctFUAn/i+6YW7+meCL8DPTu4aP7YpVLJSWYI8ekxewDu7z/oRczyyinC7towbAgdSXfHWl8fi85m5frD9+go47JbSS3wwhIJDzA/Grl2FXifwJrHc/ugCvj/SWn0oNoZMwR7IomOv9G7R1DI55N24TTCA4nngJnk7WOhyfo6gOpYMyKjkN3v3YHDGRm2wKqwRL8h2/O/Ddg0JueO1cJAiTjAAURN+hIDl/I8OEo2bAYVJwSUI3Gak//3PqLu/BgPAYoDSdMf60YAKkzwYuB8UXLo6Sbr2iwHWZiq4Jh3yF9D2AAeLbaVoZS+XhpDo/N0bJpXk6/8x6yNQKfNDc/7mH2o8l5Rg7FmJlzFuZl55YPoV9uGfDNnA/2IRyxkKEltSffuA0L5dYbIGq8NtktdsLD9fbE9jGQ64cOa2DTPx+3jA0EoiJPwUB/M+KfkA5DZNOsbukSpXubgQpTtmxU8fNSWewRyMGYEk5YvpyRAbEDQ4q9NA2U44vfFuuL4V+BToiddkB5lPGzwEuzgz0Yaq8f7fz5kMYi7G5l6LoLlWN5eOeSEdr9XScxGWZMrCPXh9eXMMxFyBJ/6Xu0z+OC4nVMJsGFfbX4JvIKavb97SJhYwPkZ++jUyjED88Vnz4sQ+rWS0/FCjA09hvmjGsXWoujvNAth/4SQboUlNqn4ednK0vV8Cv/g=
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgASqe0ntcQSFo6t3Yj/2EESg3mENUHCsx61ctgNXG+RhOpZhOrlUaZW7mZkL6lVORdH9QWr32gxT7lzAzSubeeug4uAqY2VxrR4HYtZJkmUEHse4Q8OoqHoRLMn6AmigSTGg7Z/S9agfB77L22MuQV1wopBEv9smLj9zjzC4ditoL/eoBagXTY813qSIrkTtZ1wvlF9JkBCChUIkfuvfSjbARwgznMZZLqGdPMRWeLv3z14HKJ/6ItykjKq6tDAzqFLtqQmAyeRZvLzmoczxvO4PGmei1FGLyO521quMLpAwPWccHMnIq+qhToR18l+CegWJ81OqoF2WvDmctFo2DQ3PcrIt6iX/4XjadnTYNxMazqOCmPXYZvQompp6Pt9jX/iLUcjHE92sHU93Qc0KabOTDXZw369HlpgMltgQMjHRU/W/J46F1kdlR14BkPypte0OTAO7K+sDwUwqDOuWS6EDvnOwI1wMTOo9KSaOVOVeSIxVAkhB++o37N8Ea7VFDm1FrKIGrCyuGfSoN/jnJQlhhdf28WcOHbwkh4Fz3W+izUvKq0iF7CErX5wpUIxXKDWTmdFahL0ymOtIOmSYFiKR4J1AItylrbj2OCFPNNd8PY+sDrxjmNLkEwgHFV+jMxcj8XgpY6dnCDMj5RPCaRKgHW03LEcgyLFmbRAOFxLg2oyyZqlTQ/gDmSxPavpUDY4FT7kTWWi/n05nuURPaZYtuaaFg37h48F9elg5gnafQdJnNSYhKbGADJmirVEzmk=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-matchmaking-secret
      namespace: quizup-prod
