---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-matchmaking-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_PASSWORD: AgBAM9y/yHiVYTwRRxV3UZU92WXEDOw9zP1zET6YJCfdQodvPQCCBiIPtry2AHsJ3FuGinVQV62waOWvsTSOR78X35WeothBSpq154tEOhmeoDEAIAupW711Jn/Dblb7D/B+PmG49f0cRQry6caIXmQdRB0w6+A3ciwypNz6lhefHBYRWoDiOS+acYuWMXaMbgIMRfTgRrldBOK5fq6OdQrWVeoP59wVNUgUn1y/qesZcYhZE90YJcKPzGLUDjopEkkX9vPMKOFHi9H4RxhIh2CIuu3QDVpkeYfqWaEUyf2/vMhzjjIw3wbTneat0veG6589h0klJSl954OsG/bVs3nB1IgU7ytzmdIGK7BwGekYTtlWtbS6V+gcq7dApwZafmkKn+2jByOBxdfy6QaL+AYjxx0oCpKNZs9LjZGl5wVzXb4lbM2+oACb+MmafEIRwZlBG/3hajMz/SGEuzd4izfzT+DawyHPijWjtoQFxroECBN/VzjmpdW4hUfqH3Qkh9dz2BRcQho6vfdzNgqKs6+EcwdvYX87LAdsziMl62Bf5MzHk7ys0PWTJNbMHnnMr8eZGqprAl7qQxXnFDY1uxduewjvpfYEwzRzOck9gvBWdz9XwCiHA4JXnkUfHDUqJdu/oIpO8sTfOvo/Gd5NgBRdlXuCt/W//ofUUuUrYnReUX/N5Pn+rlJ2NLm991iAORuqs64ulGTw4lUK0Id5PgXZTaiwAA7ww2OBmP1e/Hj2AgCA3TiInQZ+UUeR+HHiIho=
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgB2pjtCa10NoswCtFX3BpBYE0IWPLyRhn/Pns9NwyhEnpQ/N5kEr0h3roxyNLu3R6LNfB9yTlyz239Xq2ZYOh0468hLjoJIJ9ywtrMaHI2cyyZulNAh9hgNAnIV7QfQ5bTdcoKJDsz9sYHR1Mvm36DSQr1hi5X4roLAb9ANWpUj2XIffFYePWoTOjB2erEwWVSzbmvztgTqVZMuEVQcL5vXrO5l3HoDVuimMaLBHGJ3Nuks+BbLZJNWO2WvXjXv/+G4CANZ5QpV4TiKHQBP2UuFje1ZumYrQkEJXHg5FUgBwE2pVs5PY6u1eQa+X954WkRj9EsyCjw4PYirpVCJSplh9EQ8oRmo189xYrwZ8soy4xoXdvutqWBQ0YFxTqilrATfYNqiVonbcBIFFhW1CPtS3BlMnLs0Ndy4WuanbdL9ptJzacRFHpTZdyRyNnzWytu2PRol9ZFQmOrF4yXL0pZ8SAt/9qgxuEvs5hoZLcWomn6NvgRhuZR6/2Ow5guWvAOGZL83SwuTl3rIKWSYNS69n3CbIOODc6UI8mQ+vioSkhbTr6mnvLaU83pezY9YCa5QwPCpk2Fh0FV5+8WbtCX1IK7ANqI7CGrxU49MpZRH+VwZ1GsrcEAfQqEu8tUG39uDs6ccvgY1d1lDBjjynMk9RT8ZkdDflwqiRxyl7dCRXC3rA1jSNaydo4WR4rq7RO5Hh7YqY2P26vOMFHaGpRhePpUaYB24RyCqjhlS54ARvM+kspJCJt6142Bf8taDdDM=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-matchmaking-secret
      namespace: quizup-prod
