---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAOAugJUaiGz+CGiuk2+LwXTiKPa4Y4QcmOHUgci6Uchi42AxOZ4l6EXU3aABpCCB/Pk1o8rga1s+ktp5r6uhUtJr7ylOpD9v4g+FPJ6p4Bj1m/1ZNl1jWEwaBGemKtqalauzbJTpUIH/XIqf3LgXzgnR7APMXNrCzMNGYhhfBM+H0yszVz/FuL00IyH/6LcvSlazD6ggELyFTgPXQk0Grm39fqXSMwzZlfZ30J9INhGKP78cP4Kn7Xoy1+xfTU5Q1iFt/Ia6XRwfqXoKMjZoJW4/lp4z6mcIBQSA28QDoVSNaHGBnTm/PXn4lufohx0thsi/c6S90KP2zzjeNFXTHucEVUeAC8zAuTxJTpXz+JHYNrvMyEjqTWGHgAT50hiN+siho/EspsUBmqNl2ihyWmIx78yEAMkCWRBoUQE9oceVfwslwxQq0heGt5e4tbMvH+xgshuBwuLlmj/rxoiWDVYO3dbUMgqEr5RN7epXHr7UPROSuYEJYSzUEdONfP+9Tgh+j8kxVEGzBRbapbrqBVbrOGt3jDRqDBd9eQgCCCMNwFOwQA5n2U6NcllgclawxVE238Jj+67x8M3ExUc6Qloo1dy3PijHAekPg0PtQRFQW3p/RW8v46UfRcY30sebrk+LacWLbpTKv5ktJq3H6+olEnSUErRsnxHOpUZzK8ldkFRlq2mRB+3zHUPShdOXQ51iwktMoCA3mTc7QRvLrzDGsy2i4uufo3/9UZLhKZSg==
    admin-user: AgBJdgThVmSjYh9z6DdaMv81ehko9672NYYJjCXw1+PdMiCKFQlphgn8JzazuRQXvqnr1tFvllRYQO+VMbZO6Np0bkb4OtFI6K01K6+Juvtzxs2NQF/6CFWyhFLO9Yo/trCUoTLaBH63OELV9pYg/0jSzZm9VjSwI+6FCwOPsFwB5dg6OT8qIZNmSdSaDmVP12lxM2VcGbFd3sZycerFeT9WOZQs5RT3dDo6miQGbQ9iWZdAtyCFm0yPvmP9wZp+Pqzd44y1gb69ylm6RfKqeP5uM/scbGtqcu1ZhF0VinM7oVmo6u3fANXaUFV3pE2lSi85jwGi62/aebOTnPPwnfVOFJ0MsrA+yBB/I2Rw4GlOb6ha+H1dVykGKsVFpqoISpeWt8c9aMLhR5HsBOJ18Z2Zdiem0WsySkM5Oh/8n6Z6yCglH2SUfemycAWPL4FFIlNXXKJLq6Vais2ICuRqVsT7l7Jhv8UWr0qd3LBYrJZCHClJpen7MUQilyjwksVX+76tTXrPvH5ZQwesUPWb2riHlZMIO3kZF72tddta9dYcUh4V9G/mNJKWCn/zxZl4PVUcijgPYkWKz4zP0nmhnf0zlYAXfg+SzFm6V82AmxSObMoJHcONzwehdEDTumX0yEs23YaSWw2tpHnN16dWuruwOk3zbhEQotv9mzun4V/qzSdCphJlmK9uFDgEOeMjWcwQ7200fg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgBSXnxya0+uZaQS0fAbhmiGu29KN4aFnEd+leoTwUSlJP3B40MhP82OyvjRz9bRzMnksYw+1X2z4cCMOZYqZ+QFx8iqODf2JDrg6yK2Kn8vVFdHa6Hg8m6cxUF9AJaWoXO2hbyxwLCGZDoirJDW32C6VTC8jHhxoECMU1G+PcYuZzLw65dJuZsgVNDAQLDJdY0qYKUHCdeC88GsEzPz27I2dAbB5gG/qyyo2I+OowtPGB7NF/ptxYVwsFiP2M+Xx3V/mY2P3lwJs3s6aJ4GSssPpUL/iA6utaQy1f7Ybar13hEf+VrFR9Pw3jt6sGcJzVX+ZO8jSmIZ2M8mNTcuBJ9QG8ZM6vyWOCd8h6IFpkhQTZR099gj6O52VHZnOtNnLpHJ6DqoLuUTexv8ZX2nHcXPdwbc+dJ1VewP6er6jyVmcGi/1x4ZbckCiIP1aEHgJ0j600biGjVaimXRwn2Qt1C0POJV5KI20SJbAuXi37NBsHDduc1MQqPWRd+ibjoFjzlKERYmkcL7ENPA/Sq12rcWv0JfKbUBn+8Qa8lrrDhfNo8u6C4cHpoeve+QhJAow1iSXRHDWVJXe/z2aaQ/NMTzyQTCq8buUKhhp+lK+CPlFgYca6Wy+2hdNDPFvKYABJtXuCf3TOfHs3EaaxRVOla1HddnhY7v0XIDG8PQJbbW1GHxu4H1SPgU477MU5jhxZnIBeBRDNIZ0zDrXd/HI7qZy5ig6ZasQCSYgd+gUtKakVsxvETVFHC/KLNKu1emabP4wU0/lQXnwUTVHQHGrjyk
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oidc
      namespace: monitoring
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-alertmanager
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgAb05uxfZ3KQ5EuyqHhy3eXT8HcGHZzE5BYmPWDYCH5/7fD+CfWSH+LD3M8xUTc4FfzBTCWxID7QLbCqXIr256Ymjpxj4Y7JrnO6nVb8OQAgpWufl88CUJK1CAzb3ZOQWZVbHEFPB5O0x1nw5BapGW4aaKDQ2yfP23sc+cBrE/DRuY1EzWWUDX+apSw5Aogw7lOEj5GeIKxATv1lECs3bHgKb4NdIJDotA0gB9eZaHska9Q/Rsoj7jx53a/zswJ/9I1pDLdBiuErTqN6quNEfmS/P8IatjTW0HMNiyBk1uxueHum3JJEL4inwvDxq0p24+04v2zUr7FOUyWJru8gZT9OnrFZBa3mIgbyxVPAOOWhHmB+UU+vInbBB8YIWsq2wbPZGUAov/4v/v1kmwUzeA0qpAO1kRYHOPdWJUGQBJMvtftxa2AOCXluEjoZ1noQsy7hGHOtDxcjnMJsNL54hgjKvG4AhpXoRDw2FDUHiPtEUQsI2ALMi0illY+Q28v2pipC1WFs8LwXpEiMGau1ba9r8JVTW+T3NgXKiEv8sXomkraSSTkMS86UnvR9TW0lZv6YvkaKTV2FcGteAz/vdkhRTAf+v6KWo9aGCP5I3oN0krv2WUNZamMm2ckOeNRdJo2IeaijO7uADYnD5h+sHKcVQTiVD9MvO1eoZiweVHVra10M1gYm+oFm6Lvr1VXz2/zqxGrhsNRo9eMsnvJcDCUHpUV5FM3ifxD+DALQf4tjl9yWdeM1BAlhB74KEbF
  template:
    metadata:
      creationTimestamp: null
      name: telegram-alertmanager
      namespace: monitoring
