---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-game-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_PASSWORD: AgALXM1C4i7xtUyFalmK3uGIe7ERIS+qCfLkbLTC+YN5n5pms+uYkqlg8H2PYZu7QGLV7Xm+nupJh/xirJmsTLrwAMcAUSoEptxZaNCYNBgC4LVGyvpz8OO2IkCqds+ljuz/LwqrUCTiNAxiDo5S/b+ajXxMqGzHcFkC9TI5Y/rUAhgCgNjnYuCA1WcY2wWA74QZwii4iKGJhT0xuC90TNHFFmQI3RCHo3X1eAY/vewyOJtDZgiGNiSpNKJ2KLxrYPCNpv+IGUF/AFbU39FxFFad9kBhdwccdRfATHE1FCu6a/EJDtqJm0vCVyaFtGCjUXBCJETyuoPjIuox1TRhXC+zVZh9jgVfqEEuNdKX8KniID3wuiCDe2CY8h+0sgmoVDOGOTJPPM2m2jdMZ5IAGlWQtMQBW5+nazVLZegsua79ZZgCbltIthtfvDS/U1d9UX+zH/zGGbWN5xOf0tHHhfXq8zekCr2PkAyUaLWLCYNB50s0fMcs6eeFZROQkHrXkEwGXNMwDMP0Ntufk0otPFVbo34ASW7QY1Fo3puAgCkH1GrF0uybJGeeL538EG8BMmtOE70gUKQfL7gUc+eV3Rd6JAZeVxvaRS1AiUnwanZWQfbQXYW3FLj76t5JJtS0ahcy6m6ex4GGVcnejsA/nx1vZnOu3enQ9LF7UseF/elil8ERmVLl7uMR42/B/2nCV8nj5ChTCdN5kKVD7vdgxjOOUBD78ByOfPn2qRj2rmTAXsjfEG5w6hgGyq414NjTcMI=
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgA3K8sUM/EIRweeTeN2mmc2Lu3t4enial5qYN3/9b1aNYKpM/oUvcxaP1UVB51yc3qayke1T+0Oj3mNsyjbpJmJW99Q+2o/+yKnG8xuLMUIcvI0pRkyoQsoCMKf94JfNWQ5YsCQFM30BGvDm7qvX3e1NIkydbSEYXDau2vT3EpUPSnpAo/M3o1QPr+pH+lmUOJ3D3CEL5toQQTPCVeXnPIJp5WbjkfXjSEc+WizBvXMEp/D+1X4jHflNuZUUEW5z6hvrnrv3eMS5Z7VgrkLw4+uR9kjV0tjSL9k5922vEScs0T5/1CtU8182ptc6WkSHJlRZ6OxNNdPfFlXfW97VoHEK0alfcPOzTSYndYKoP57HI4GBj9CHCSAKhjnU5p2mMaZOvUnxOoGpgT/5YuAZZBf7KB/6XStxqloypFs7f1wwpFhsenkDbxGly4dxZOKUCn0uwJFZ68ptfklksSLo3TClBrzIOmXDi3ijAXruGy2T6rKYqXXnc25xDhMrkEOyNj+3VcYws6OagE0lU0V0m2CA7vPeYQkCv41odnsPTdAqhKqVp3nhC9Aubht+O9ApVedSDt6R8Lbd3WWuS1rUJV7Xz6kB9Ro/27GHL1whbcORyKEn1PBrBf6YpTWFQLShQds/2ZNUpPHMlzJQOZ8CXAX2PJQEGM0fjY7t6Ox3iY8rkuW56LBl+XDR1aS//5FrcJ87YPcfOTMkdqfQ6n8+J7BaddT1P7/a/77e3IF/QuR3gva2V5OhkrEUTIuFo+5CCg=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-game-secret
      namespace: quizup-prod
