---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-game-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_PASSWORD: AgAci1gQbyot3noJgxnXhP5E1MKEpl7CcFkJ6CqG97abaMw6oOA9Ogoi2+v3oU3+Y7DZXmtKxCwoerJcXhi2CAycER5KQsMqHm6e3CC8PiTtJEDVSsTt1Rsl3UWM7yTsu0Nau2qxfEKuXkPCUBCDmUI0LeD50adX7evzV0u4rZjS8q+EQwHmN5ewwfOPN2Dm9nr4rkzmFJ8XPmLIapJnOzfU7fHLtMjGud4Z7sYLvpmQvui7vaMauaWpoqkT5WY+kJb26GpoSUoYVZ5zHLr7w6bzIN28Kr+nSFpjGZclDsDSawtwkuQbkf0Wqepc9TYgKFhIywBYXGZIF+QITEGb0nhraGbTeSJumB7zTCTAkbnXaGnO4OLfXtPbkQYUNiUrKAru8yzj+FDK72JGFdRCovjZQCzlPFALd9mGVMmHE7tPbB+SPhAOjl+ZyZFivX0BRiOzESnQu2j2K2SnY7LgKgVLs65+wJ+7YcPP8k3oNs81FpybwFVhlzaERnDQpORaCuwXfMaETTHLOjb3LlHcepKVXWD/8rvkjy2XGa7EZkllyyvggapAFJDRkphYycQXZhLM3EFbVT1y6JDZ7SaRYdDfCmuNv193zbkBX1t/OiyGlMjROCIYf9tW2b7uelvFd6uy50NQflE5H46OsLlvo4Vjt71f4cZ9iGfkeNsSAMocAwEqLKo0TZcnduE5KhPQ81qssLk07nWwS7uHrcZBDI+NWDAgFo+X5JsyL1xTVVHz0MBuDugmTkdgsHXaDNGqtmw=
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgA9RZ2e3io5aoujNtVNm9vT+csfht+TbioBEOU6WT1d3UonZ6rDInwc8LWTeDl0XN+7nXnDJc7QHy3mA4AYmc3wmWza5lg2KlrdfkJbSrlhOA9VFJsorr89U9T7g4FU8uU5HKOCdoF1WoUFyP6zMiwuQJZyroYmHpuDq5zMDjyYnCEAU6np6SG9ckH+0tLkYnbSPtC/t2XE7uh+qc9dlMyy9t2lxjJRZh5d5w2VQB1ICj75IHHf5d5xkH5QobbC5fWxjI38VUyiiImvEObqsNkkBjnTal5ADupUSgBJ1qnnsOhspcYFbR9nn1h1Jkt2m7v77oq4cBANJAMRdlQDoxYYX5aLOZP/cT8ALhuHmXg/a8c1Wzl/TcvGzXMNU9iE4yorTZUPeibpKUV7Kn5v+MM1q3HY4Por9amSldQypNagFB0poDPikil/K3+brCAPXKlFjxTxJ8lvYWzE3yZsj1JwTvGasovCxivjNb6lXXFZnb1J2YhEzFXy98wDifaWMSjSP0PfCYC/yR/VidnEQXufQJDtrudDLMDZJWY74ohcAhoqlitSTwaclUvKRsO77yAGDWKJdaIs0fCwpd34Ygco37Gmjhr3yT05FdK/OqH1KWEO47yih7GM7lpFsbrbNnpBqD2kX0LUpfFZcjrrZ6BerFDig+H+tl7rRToKRX26M7Gfn/nXmpGUIAGs80m9tnV6ZDwCihViae2/bbbRUzABdWv4YOuQ2kYoG1pMk6SnjvPyoI2iq2a12x7z9V/kMO4=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-game-secret
      namespace: quizup-prod
