---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-identity-grafana
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_GRAFANA_CLIENT_SECRET: AgAWyaJdf5ERvRjzW4rXTjeL9eYXo/1/kRsNGr+9rKl12PUDEkrVGZV0i8jbe0jLLiydITJP0wn8ClPOVBiUYJso6CJofbcl7I6oy9GiKuJ0LrtRQZgb9WTCkqbEb7juY0R6G9d9RtIdRPWnTCsttf1z6TTkFmXrOI84IJQ/fGv0LjY2ft23UGm1fqgux7rUUE6M8Ot7BDclFe2gzA0qfYWZctFYiTgNHf4liCTpT6YZUYSru4IrtG8FqZECMHLcrnxbTiRy+B2eAJ6KiDU5LNftNE7/AoXF9FMbT3DiXcHdiR66x/Z5APXSdN6Pgfpp/IsyvEZbQOv5CHpnUZ7UrK3bUVyy6lAI5DUuXmsuFZ/uCCnNSuJBGeF1XeZbNW69ttZd6tl4agyV0Ftgf/sUWWFXg6r0lsejWm3oNPXutDBMUXv1zaOQ8KAg7PzsL6P6ghoucKATe0rh3qdEbnifwNlEQN0DDlyPNByTYOSFOOjoTlPNrtqaXAcH1tz6nm5BJfvhY647kkf/YQvsln+6mZH1UCbk4etXDShMtu5sXoB3SUN1X1gk9xUqBIvuvQ6BUmhsx/xYod4sG1Myk5RXT4xu35aBz2IBm0ja78rS4EVOd7F6UXTTIoF1/3+4yR0HnsNa/JmQScBqO1SHKYNhLqxPNSMDAzEb8x/J/ZRhyKbV/Fk/LRkLlGJlZIYChhzmdu5F+kBp5qvzNF0CVilTdqwy8P0vwsYW9OjFIu1fxburgJdkK/dpiKvzfOWlnlzSGcZD51gcBCRYu+N3uuJ+qhf/
  template:
    metadata:
      creationTimestamp: null
      name: quizup-identity-grafana
      namespace: quizup-prod
