---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quizup-identity-mail
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_MAIL_API_KEY: AgASmKvP8lvWfNacYPvqkoerRp/C6YadNYdsh5RsTc9VWm5QXrHnqAJfIVOAoxNFbsRABwCW9huAHCdIVbz53ErJimRIez0dUkg5i9mngzTvMOQfZJommwMZT6gOOjfW9QDYvh2ooaNOofQk/2Pbt5QDSGdPypHuGTe5vFTe009Jd0xXW3dk1K8/Y3KjHnueQ7uoeJ/DkM5uvGI0OEKX0bm3+BcQgrgN3M5rwYRqPTn8MulkItI+P4GouJkz3RtwaykjtH3MJJIo3Havf1DP+boltwN6qfOyOY5tzkRzSK6chRRr29TMTBCvaA2o4gp3h8R1uHtU0PnUltL6gzlO3rCVFyXQ5h0UYOQHLH2pwTlXyulqMP1btNLMB40z3wAZAny9Wl+IhG7gzfcRq6jxRcGBUNJFmhZjoN8Jh8czbjJpOvf0suHXKTslKGEk5RX3h8xM4ZiZErly/q69ojte0Bo7J+BCf4AR23KBVhqKsWO/TS3qNZZ8g2dZUt8kIfIHh0A1DTSDnd4jOAHftbQ+XopRIdOCl54ZaKpgWweF0SMWUu0xYE/D6m1w65zluY8V+KV3GyUwTxVZYi18RMpNPZrwjbw6c1groKXoaqz/NCjPb8WUDvSa1qik+P2gU8h5KCPa9Z5op42nZFYeDv3ONsIdUA8ToGqYQEaJ/g2vzthXWgbcTDJhj8Csc4pm7FP9bhIPDOKlEyEk+I3XVjPGPkq4P7+tOfHCrFJYUcrhqwk1jvQ+XKs=
  template:
    metadata:
      name: quizup-identity-mail
      namespace: quizup-prod
