---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBCPk26LeZyw9SWs4PgojiIzyznzzA3VBVJ1qMKp05sKj6bIIXkDTqvvPPkG0YHON2sMxlFXqL+9kPy//EyOudfg0cCDAsU6N+xP4B7xKKCLsHNvYrxGGxyg0aDCZt6k3wW5GTAZ/XrcXIf9zI6ZUJFvZ4VYLfbWzg6k2fJqcMuRW1ype/+qjrSCl0YVkQnjD3FFwPCfQig2nAVivmsK3juBsrWTBbaiqMHKsOmCfEiGNJK0S+/PSNmXOO3j2YpdnCHv38Tq44/PfiKtlay0H/3+/Cff+lHrRTrBEwVT2M5SLqa5Z689Nz6BmBOS65nIiJkovg3aKX+mq/VwPZ9o2YhczOVQ6qsD4VTfIhOVF20nJ3bL/hptt9LBvDWnBiIYVihe9am5TXt1caTjjvx9BIgQtjdXQNFMIQyzSfa35Vml8WYgmtojhV6LbeV+4e1cLqDprBJGqnK1UIYE1aDn5KHf+VGl5hJQFtwKuod50FQMrfrMNx4/wLwfitXDt1OuvOmyYZRCu87ovPC60vqWRnvTIJZJHN+XrFJHKbA8mxbWqWC26GdIfdyqN/IN325SWFiVAROK3jW8nCcqatyJFSmT1+cVNppzYEljLUOuK7GZ7zLwb2RXLTLT5NT4VgQM384YLzezYTsRqpg+Xa42aGZ5wd8qgl5zPSut0xmP3+JO6/qAPTKTJo2zi1QnNKcPXPNR0bpfKZfNSiKm8p7DEwBwxo2gIw+2F41pCecNuQJC+qNAtFrMv268gnAe2IE1JhKktHJh+zN/TYmJu7AEqz07DBuyi81JHclSTAVnwBFpf4rhVBdXtT3I5DNYegyHKiU4ITOO1D2bmqaq9V1jiIsOlTl1kBUMX/W3SmRP8RSp0QJl/dChRuQDeaUeh1xrR5pGl1ivArlpWY1CqRa1RUezrd9t0hqP4t144sDVPewyaX9m3jVydL2/IqylLWmTdQ72AmKI1twgQXj
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
