---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-leaderboard-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_PASSWORD: AgBeT2UwwE+CvlmQFCdcXqN5GdDTZ7ba9MKfqt6jWz9b/ZlP1BfDdHmZXSpNiyvrHkqvGc0Bn2DQTzMdz+5O7JLA6Z8bLjVnK2bseOh6UobC5gBjUzlb5UxrkzkW7/oMbLwsMt8UpqxISsdEU7KfmLMaoZ0nDaG5xvzoytNhO0q6rdrUjJvJlbNV8pPLs6D61QAq2iBBqdPi08gFQ6mLqWF6zEIamrR0YuawxIfhr0tNIG/kbYTdgPFI7jUVWG6GIdQwCGec2bVpV1NoU+PsJYLQqxi0BRvUCVrhdylJtbdufTTFNUwUq/0wE2Q5pP+V298RpUHwmS4+3RN51xV+BaTzrxu3SgrybN5wBRnLy3FXrYjoGzci6LZbvGn1e3D6GAgrGo32aKBtFEEoD1y7DHaHToBq+UmCxpb2ZAORhvnsw3UiOIx24D4fxwqJe0OQxwMaTILVVAftAVs3HsGIN9f2+Tdr/gHVoFyARJNrnCyyhZ4WbTvcoxI5bEi4BtOB51xSib2t5epWeRRy3cFhs3OX30gZgOO+nAImvyNO3qOZCuqhwO68QOdbzjSfmu3Q+H3w9QIudeVZr7BmevkklhDHTaM2+kI1yB7nI5ZNjhNlZr+9mtT0xGeCd+sVHcRvtduvSUbAdmH0lawbHYVWF3gSpQPVupvZcRFzbie8Txvl9GMVz35ghe/Rpg5Z/o3wkzeK2d16HKHAserRxe7UvBLQyCuKCZyB8hKV0Fg/9Hj8vQGE6g0DM1Gf0lPYqULgwEY=
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgBifWM87JXTApQ6szfDNIW65wHb3fflLWiFVp1RzcfiCPkvNh6AWb7j4Ghmz6KPceRUfW47SdrNNo6LXq/SphxNIm2kiK3g29sl+3aKBmcu1kxa+N8Z4NTSgAns8X29Mj7lmVS7b04+oZXKo06e9Ow/AXvWNLlasoJMjJf6ABfUw8vbh7qeCSz4KOnrDExMr913FEU1jEam+r1G6wumOE0OdZXQDYtAvc5HLtH/80hsiIvKUAuNTJ0rnYbGI8ehIxEoeOSzQAkizIVr090AKoOkAle4ogYDZgtuOgLleg6pWsy+FLQ8Co91FSB+tZTp4CWJsuGJdVTHwIARRjiTXXov/s4IWfFYBlNs1iH+VrXW69GW0757Ygqvg9HoPoQmmppUCHD4A03XNyBSARcs4vbrg4+uYXfSy4KAaXsB2LpW8NOF6lWAZXGpznUszDHtSTacHeD9D2PmbW9ueYLjdXYOewJgwCdR+y9D7q0+PqZeGRNXSIoiCKHIJ1CHcd3kJKeeTYkK9QRx0IQik9kK8ek5vz5j6EIrB6WBXH9tCvbjpnAAd+k59Dz92LrJMS+5fHvoQ2sHIwcwMKb6Qaf4ABjiViGSkviP62Loxvm2W/LhoF4ZXQbeAxEpsIo7Gur9N6GN6HEkCHcSqKk0hKemhadFQltxWpRe9xDrnRp0rvqdGsOV5gwCUAxuaBQt/j9oSBAaCtoAZ8zrZsbLgrZ5d4ewKDlLccmxIw+u2UhxFUBMtf8eaJvEcjZ4yy4LBFDoVRw=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-leaderboard-secret
      namespace: quizup-prod
