---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-leaderboard-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_PASSWORD: AgBLr0ST6P0pcIUmq8fkGKhg0Wt1GBD0IifcQRG2yWXaiCo+n0iHIckjkLj/9bre+5MHFSzvMX2cpuvHpiRc44X2aew97G2It5asDgt9LUblqaZ96vyDW/1ir5D6gbJZZ1aLwa+PSZxe3V/XnvucgpAhcyWCmdwizOH1PzAdhWERfWBDJ15M8PEtpa6zvovG1GL4dhSQBemL/+7O/EtYTwSjdLbRz4vG06u0pQNJcQSw0LCI0kvhlr16vrDF6cfJt3s2ZHxFNZgmYPEWM/kqtXtJ0o/4On/SCj2zvEPJ1C4D8JDW2t2f+NszwMQIJnJ4b0KhTXfBqhbRNhqzgMa4KC57m0OAEEX8T4XJ1O8zhOhQWTTDMCTWNqk3qNb18bHtSKepyTJ4MmAU1kdBCrYhlk4G0cFcgomPKbXEyzQUmlmSq4zScmqiT3UUJEiSWhya5r18TcQm1XMQHoEo+v+A7rVYShhq5VpM+0LYksuYXk+kGClw4pGSayEeKk8jxYLWYWCdZZ1mJg6YJA/Ebjci9iwM9osQ/VpN/Tppy/q47JSVK/mf/vqOk6r06Oke9t+dHuz1dwaHjzkLKvdteQKMT/FcAdy1dOZtw39jFDQCMLKhOUHxoCEey9HweC2mo7JTT1xaKviWa+BakiHc6ZC+PopR7GfZaOg2p3L9/qIQwdsb5sqCLTa5ans8TitVPgm6oUg9IPmVW0BaixDMesBnn/w00gtm7UYAMr0sqq1ATLlb+70EKbuKfWgw+C/z8yAu7Kk=
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgB4lUas/Hai+nXPu/Sa66SIgiXAQk3WaxahWH30uuv+wb9YNffbr1TVTlQOqLa6npLkBtEPZYslttRbppn0OPMR2NppxcxIDPgKh0A1JTkReaJzw7G6zapWd6mkCrIgDtkPTtidg4SSfB2nMJvkQYQRZS9uaN/gIPyH0Zz5Sptj4N6EMlrEX9p0s2OdxoqhnNOtysajVgLCXoIrieT2opfDPCX9HIdi0GGvaUhHHMeLA0ESi/71EB/IjweAWY+2pZOaiMnGxFwxGwO2AygjWkeC2kmO01gEBepD2mOui4tmPTAb3ID2qo9aCf+conq7gDdDjrabBI8S3sJLqtBNeKXgTz8nxBJyVgvG+dMw0x4yqebpYbqxRYM8qfb6+d3kOjcKRSA84ydwDKj/BwurMCjkPds+pSvr/GQL0rVm8reRvcfRGFMzA4Z9vh068Tkg/9pDgVvC7ct8OCBeH8ojvR2a5dBQoRkMEDnZhNvOsWC0giqnxp/ETyOBOLu+cCT/4L03B+OWEVs0XBJ2QNF83ApjEVtTo+cZtORSQbLkhXi4kFuEKz0HlbaOvVkcQ3aRAC2ZYDphLOgqExKrLIsrKZpPq8T1uOM42LwchmdxSBxuHaXV6cJjz9i6Gm1ZM2dKlRnqFJcJc+KCS4WwbWf3xWOLHE1jHCp0PqgabfLYys90/u1p72OuSFmFplBf32yvp8i8HDPOZYYOlnd0QwFu5NhJzTMDDcJqNgvZ4TMbHmbvHkGuGsEI9sI05AyHOn3SQnE=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-leaderboard-secret
      namespace: quizup-prod
