apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quizup-prod
resources:
  - manifests.yml
  - ingress.yml
  - sealed-secret.yml
images:
  - name: ghcr.io/quizup-organization/bff
    newTag: "1.1.0"
