---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-bff-push
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_PUSH_VAPID_PRIVATE_KEY: AgAvix+sjNVMbrJoAjkbW9ZHTfWi3daQOJbSjEneVSPubmS/Ni2X6KbYcDZWAKgXvPGSgjxL8puIZ/UZkuYm1M960xKR52nejRqwhTJvAkkgqG71hVsg2PZ+t3muAzqa9aN1W5e5ZyDsJi1rW7iJ0hUh4wDqDnGMxCbZz4oReUyyZkx8MYgCJQG0DujIe7glGth0a/7xYGmAM6lDPom3+kNa0Zx3m6FrkmPK+za037EOjcePS26ATOAprZcDWH54UXd6L08lPPBvHLiDzTDMw7thXLd4PWVfRHGBGGGBjqrXSdXKH05MbhTqnMKE0N7cqwvwJNVL3rmJQqQXm5r0BMU9O7Av5nfCzf0I+5JdGtve1Um+JXuhb+b6O+V2wnoI9zuJrRhQkZcj1GQ5NWzG8C6hcOn8CL7Aw1zsfkhisBlNlEiTSISG0QBV4jL9vmLlPHsOV9hm74IlHwgf11fN8IWfI/V4AcKwnEuwrNoZ28PYlqax9TPENgq0mx017TX01uigY64BSveGRak9YpW+MLp4k0WnWACqvyeMvZZxsPZPIt2apE2mUNL/qNJVJNRw3LZyGYXtQo/CfevBKtHFNMZ32+ujITTUMgPjhbmxGlcMWtsrJbBnbOZ/oSoRoZZdVTbiaPYPrl/Xwzjsgl7bGTFHsIQqzJROi88Hu5gN2J7L+f+ChtTXW3e+G/fnEy3f8sYG3wtoO8snwx2qqMoTzBE564vJq+ILxgpFBe4ed2Gik0ltAqMiwoJlmM8E
  template:
    metadata:
      creationTimestamp: null
      name: quizup-bff-push
      namespace: quizup-prod
