---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-gateway-secret
  namespace: quizup-prod
spec:
  encryptedData:
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgBAm6QYo7vt5zX6G2EliV/3Wb7dRCa6n5bSogQbEpsBo1AM9N/f68gQ/+o6osQ06FbR7joh/sLr6NbAzdUaw/PPa1q9vrqLzY9ghABF0/FVuzXgqToiNgy1i+a8SbGAvQfJzJv5fBlHKFlWQaBBTLYoL4Rg98PDoAncthcFeE4wfY6BfzUYTCPdwlm5Uy0mzNmZZJS3fnEzOH6so7KjOfu9OCadrEeI8PJUHI50vahDX+qhyBbVnViXcejVn7JGpvHdDr4Lz3iahoEWJobZAQztJw/Ra/d/+a+vx0YaZ1m1Fg8eiK0NzGwZismVtY+VGVrfNZ2tibR+jxzXGW2DkgELUAidjjFNOeyTaJzAv1ErtkYgXAGOywQpwYaxdhaxz2osV4OHfGbsMlcXpJunAMWO1ZNXVSEKVTngPWdcaJm/xpNl1wKE+HToDtzMZDXfW+l0fdXiyAQIyodGEMfUtPdlgLRmZ8T9MMOlAzc6iDZLNRX6oDmagN38EohEFbLnRvOkD8yMdg7yj6fCXAkBiuNis+KCm0Y+EtrrN6fUYo8FpsT6JXRY/twAICEoc6iREmrtaV6eCD7DUCz+XaguRK43QPM/DZUHaPI2dHDPbQZaCSflweC4cCWQZmXZpQFHTDTenK95B1hFEVh/2JpSmvN/Al39b9yfx6zhe7B0BSUzdHTGRkMy3Q/6XoYDVT2Zc43RH0xE57Wcr21Xh97UpLJnCJY6GQWntxC1fFm3lXwixwL4NJxV8UQguOSMcQprIKc=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-gateway-secret
      namespace: quizup-prod
