---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-profile-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_PASSWORD: AgCKMvLG1YY+FhxfCmEKSDDDxHN7x9Xn7dBg8v1GaMg1/IMGap/5N4+1TFyxlllElm4NhvO7ejRlPmP1Nrs9Ouma5XISApKeHLTP7fyNzae4EZYRNE4ix34TPk5iDeeF104GWXPZFBvo4n8V/6OXHJirOkQ3o8V2jI8jJkBAUHLGKk52u7IKGoXG6onqNQg3aIjLqdZOc/1jtRg347pbOWRz4JqIhgKTIwjvHf07PUQcTb9fKG0NJ+WWg1SymOi5LIDPnonZwaxtKh5KS1BejMyl2Qw32SVWLkKJl1khoJ03CTQ8IAsbpwax7ybhZ8GcxPgVa0tiGBfS08tvz8tEAwkqtoQPE4nmgOM3qVbJsXyX6JfUu8pPxNCFEHAkslBR7dK+dXybViY4H35k+dp0Vuiwqg9AVr4FAfBoNrjmSaPnrMxkTZhmvgSefPlMkh5PAAvnRah6frGFIwA87doz0fl18CvZD7NLTLIYKxevqWkFYUWXbGTElFeGOZJb8hEwbGo1xLGHryXZfwaVCI2D7TRQeEnvYV7MQRZUuCM/UTu/mtCoY52cyFFZQ/6YPVwdxuqGNBpbCVpw0wnlTTqsP7moVtb6XL7ktRJY17hr+f7PoJH1kCKGpgCLpTuJocxHR/3ZfDx0YvGXTVryoWWGiJMs6QofBlKTEYPu4O/jHsxOUXPEkhy0AkhkjJzPhPDuD438+z0RR9kK1Rlm3dSQg93xj34zKc7R8trEthMYzxUontRVnFitSU4GOqw0p4IRZNQ=
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgCJ6JhUxAICMXwKcH0lXRT+7zb7eShaXaVvQQe/cjWJLQSTZhqONNU9ons3CzVw0sH+FSBeSOMkTf0SnB80xHdxcr/Y2E02NsmrS24bl4lkgOzAWftyPRg1rbqn/hqe4uAUQ95dwe3why9cKO1Iu7lPRvlNH1xXZZXwtKjncMAIVNrdTj/TQp/R/mEzqiJq/07b9ju5XFiGX80ybZx4GV2Or3N9HPge6RGXZhCK5N50g6Nq7XPtIuRa7Q6+juMHXF1a+VRIi/IKt5s7eeUo9q4cV4GekzMPJgfevUQNr/twUDI+QSJOd7uM9MgT5kt0YovCw8mDR9MovRkGP2YkFvX80HF+SIpMszv9YUGCdAewS+frPRyiRaQbzPhDKMGryRYRogUS4E5g1AWqs+NLw0x2QzNjXeiJVok41YyOsm3cycEPSgEQd+1qUhlrCb4S6gaozo1pmSZiImDpzbDd/KVhEtF1kaiGIsV23M62UxeJvxKXZXH8ZtOFwBbZDvCuSynh6ZZJuVvjhNeJ7qmwvPDXOsOiHHdu/3VFn3DNfHi4cH8TbNhZBXDf1LEvVe7rrmaDlfR7MYSQ+ZxWUc42yssFdBd/Mo/eHFrasYLic44lCOH5rhTplJNUQIEBPeFxH8o2ggri++D1DmYxARuGem1om/NyWNVH6RnKGOpf5OxwMCowF3f2eJJS22zM6VAaduIUOKNgobSeHYOSjMBLRp3+Kwndie3kh+w5FsA9A6B5LNrTbrT2gtL59yFXqij5VNI=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-profile-secret
      namespace: quizup-prod
