---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-profile-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_PASSWORD: AgAGl1g6DJgJTufMhGEX9Fy9/Wo0kASlE32Tw4CJ+D1qT7/v+LwmuciV0sJmvA7e67ns+JjhE7R/nDdIjGLBa7rh87pdfY/uwyCv9zCkgCCEZJpwFH5vwKY5VJsDSTT9QVJKdj8c2apHD6WzLWF1lIoEwoNs5BXVy03/u3wOJR+mpF1P2zd0RPOm0UDbj9PmyJDZ7a8LRURtxD8blHzkSHp+1w+ABO2sblprmk2zS68ftaou+OXsg2TbwGMt2/1tNDRuGHAQtHHbyac8UgIKXS3b2XwTatRg/OetwVQ49yWzNMHdDrpoAxQvuCL5vybwiFcGsUzPUjIQudAaucj+NkmKgWSLAzSTbQbcmzR0p48kjXOgcNujgb0QrVC4ERZZDbm3ybSJdQsPZ/KGRcXe+0UStPZngX45VV3sFJ3PDqGQcQvcLxXRMwdYeE2avRdXiahB5qcagS46yDxuJJhOEyCl20UlxOV9CQYQAyd4diUPrVsF6VixcHZqG0l4We2rQNR4CtLA46h26v92UOA0EyXNrQ5jax4tgcDJotYXzPHTXLNKNEZSF5+XpsWLbuRoITA+h7ALBP4H4r1BoGFt0awHQlBoCTjdNzhLcZdTpIG+9S7GjV32Lxhy30UyAS9RShvIhIyOtxuabmqEPogPR0oXUUNfYXqk2dpP9p14N71Xt791QO929mB6HlLfH2+CIT+68ifOR7xF7qGr+R6Jfd3VO3yhMYoohB74oRm08OZLgZLrvKFIc+Ni4CVVeVky1gQ=
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgB24DtDnSGLblVov388khIIFm86Wm+yiC9L5MlVeslXQELsn9EPWhm6Gys+NTQq2ENWMkXPJdJHl33x+Rk0IIE2K/V4Z4dq+gCsrCZs5EeoWjUemYuoNnxhPOaMOTDuX6AgmADP68wtVc/2SCtzxsUNXrdhozA4p75CgwaHNgSVI6d6eB0q1HLPfZAY9wW5d55o5L1elr8INyUk+0LREoe9UiI4dQT/OvPXZAG5Z04FGQCaNDimfEFkX9/0llL8wmn0nAG519wNCjUXrZSC2V2px6hSCcx9lJYl/QqlvJVom/2Y0PCndnyZLQS3iWoCRG1yLCKcqtmgPqHXdX+98MvVzDxFmIkJ2Sm88Y0KbpG08UtemVEaaStyc+n1qqCbH8qxDUR5/exuMDEnEjVbJbtVy9jJxTlq2n3Jvks+ks1SCSmWJwNSjOU74HiNVTWJDTryCAFTuGU7M2cb0CS0s8NA6e1apQuwYUtvdL8JiwRckqTgIlyQvzJ23A/OnxoKYDy+AqRB/QJtv2JHEJtO89EPAU/jVScW3opw1Q2s00Bz5q0JNo04AVFXRf2T43+6boz7TIhQyycR3KWYaLdhoqTPPbbpVuAMsZAiFUkO+jX0db7RYcy+aeyQw3OMGVcXV5eLlmHlFqiFDrzRjmr3rCtf00dOHt/fufnPxhilaiXs0s2ojxQyndEZ1VSl5OVzEjCZ51TxO3jIWHpikd2E2tblNxwhiUrzjEKf7nzsdBAwQKwGJa1mKmlllQi++EI+8gs=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-profile-secret
      namespace: quizup-prod
