---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-notification-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_PASSWORD: AgBFAPSUuIcpc3k2fL9h7zFDxf3peSm9ILL7Fj40kjfDm1lOR3gZcTn+OZ82MchOGpvhI0UB8f9JxzT2qGjALOvYX6cSyr6kCXE4ZPwL2bJO9L/zqYW3Rj887z69s+3txvgNA5gCZCfmi5BLlODPz3mmLNhxlFcseGaKt5kOExtM9lTO40mtp/LIHztu5fJxPrUXa2iaZiWg3m4IkgoOzKxdE4tAxICIK06piCIvmjAPThuoI36o/HVWvgsJPC2Kf8TTWSJ3xq1QFRhzPORweI97hUGOJyF2XI+6wZhD7qA+dAijv9+h3v9i/jGJifB1ST3XM0UUgp8DiX5Nta2mTktqCFwYED0FBQxIPPqwqqbNDKENVHXCG+ncjHsMpDnJYhgFJStrULw1UdHMlc0XR/sniyB4fDmYZzjL5/4oGp21Rv8u/C7vcpzpY+d1cjrNHmhhRlidEYpW8eOQG/mTCdzF3O914Pd89151/C/RhyQNBEWZ1dwW0r1KckKrNyFITaTgl60hHqF/vTubJBuLQjWykJyJ3L9gsRR26LyY9letf5H/bUDT45H5IyD1d9PxJQDUN3kvs9eopsxNTqUpyNtgVxbWTs6LZOrN8z+HVb1KK8cXmpYQF9hCj9AL4KQLoZT1T3R6ToRYvNc2YeAMabfrYRSeJp6dxspaHh6ZeAt6EH6Z5Z7CgAG1meT35LI+Mwx1KEyuRUihf8QBEjqMvxqSSLW8XUvn006mySn9X+JMn9neaD8atW2eNOUzVzvXDkw=
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgBmCwgOwSNLW+HqdmLN0uxxOEbCg0znX6IuwTs5dNnjomVPmKNIH1DlG0455jAsvKufdNnz48GUZXox4yHu2Omlqm1Nea93ALAPL42+s18Pg/kwUuJ+xfXiVwa7PuPGGDe1lgHp67u8suaGBXW2dZFP9SlBb5yDM6JkFeIaXwh0MHk61aHg0rYoNc4KMi09U+fI/PgZwFfwMc/aRicxAzmiTLNLJnaSNWiBrq0+CfGKe6C45QDEqkFmFHgc0sSOUwXtyEATqlTTd+542B/5sALD4Z+Z7O9WHdoI+kk9x+KVKiZ6mhDZX8J/OKmL54OPztuQRscBuzuy+sOT6z+5RX04Bhi4u7mKV91m61sVDjHUR9saU709Y2+H244Y15MfUJFBz09D+KizoqiAlqWWoJcnxMIB2ojWDa4RCVDZ4nV4HglDx7MaYUhoeDuFqa2Ed3N59f630YPloiPDMebIHQnr+rKr5/ZbZLlmS6Uo16jeEh6fmkR5Qd9MyAWmfB2KZDecUntaZ4TZ8nhWZWkvk9PmCHypB+B8VjbPVleupaMB63h84TtvEq/OLdks/CBUJ3OYrHEgmY5YKNaxFOV/ECs6D6u5/23RH2pztSFnM48Ix2FULDJeNESAT9R2P1+/soJHREra+7AUGQyUvu0gV8UEGQ5XCz+f+OXKgYkgry5p8gsBBlEd9oI6wIZaDPtOAWVxsXPfLpOz7MJq9dMbtIYkSJAZ5rg72OGADoXYxacyvIEUtvsqrKEfPSRdI/PKc1E=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-notification-secret
      namespace: quizup-prod
