# Généré par scripts/seal-secrets.sh (cible `ovh-credentials`) — NE PAS éditer à la main.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ovh-credentials
  namespace: cert-manager
spec:
  encryptedData:
    applicationKey: CHANGE_ME
    applicationSecret: CHANGE_ME
    applicationConsumerKey: CHANGE_ME
  template:
    metadata:
      name: ovh-credentials
      namespace: cert-manager
    type: Opaque
