apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-ovh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aureq.github.io/cert-manager-webhook-ovh/
    chart: cert-manager-webhook-ovh
    targetRevision: 0.9.16
    helm:
      releaseName: cert-manager-webhook-ovh
      values: |
        groupName: acme.quizup.cnadjim.fr
        certManager:
          namespace: cert-manager
          serviceAccountName: cert-manager
        pod:
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 192Mi
        issuers:
          - create: true
            kind: ClusterIssuer
            name: letsencrypt-prod
            email: admin@cnadjim.fr
            acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
            ovhEndpointName: ovh-eu
            ovhAuthenticationMethod: application
            ovhAuthenticationRef:
              applicationKeyRef:
                name: ovh-credentials
                key: applicationKey
              applicationSecretRef:
                name: ovh-credentials
                key: applicationSecret
              applicationConsumerKeyRef:
                name: ovh-credentials
                key: applicationConsumerKey
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
