apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quizup-profile
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/quizup-organization/quizup-gitops.git
    targetRevision: main
    path: apps/profile
  destination:
    server: https://kubernetes.default.svc
    namespace: quizup-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
