apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quizup-theme
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: theme=ghcr.io/quizup-organization/theme
    argocd-image-updater.argoproj.io/theme.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/quizup-organization/quizup-gitops.git
    targetRevision: main
    path: apps/theme
  destination:
    server: https://kubernetes.default.svc
    namespace: quizup-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
