apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quizup-prod
resources:
  - configmap.yml
  - common-config.yml
  - oauth-client-config.yml
  - postgres-init.yml
  - postgres.yml
  - kafka.yml
  - rbac.yml
  - sealed-secret.yml
  - registry-secret.yml
