---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull
  namespace: quizup-prod
spec:
  encryptedData:
    .dockerconfigjson: AgCPq+ks65TZYzC0qodGSSnMUo1Fu/Z3uusJz+jJSWiAiTZH0+przJeBrNU+BYuxAO6zDgY4eOFQ26aUEn07kGnDl4arCCggHY48l8h/5LXha2aVSRg9UoIUGLtt5X1fCShL6/uf3cWVmnRcWIGWO2NcasznikKyBTNeVwE98ed05BNB8r6vv/pI1ZmYfHqlxB3aul6BdwTbbepMMWMjDDirOyznCYtDcaM3QH0wBRVVegkK8gCYS5ym/K5OSLB4905cLx6E6+w9swXgrMMVQbXY99XxHOmF9jUBRj9IWvu093uxmnXbzMVf/mJh59QDZq2RvKY6VdK1mc34miMFFr+s2OuKE4cVIbysK11AnI2Mn8oXfToOkK3qUpyILjJZr9XLI6WXT+ucgY8hd3mHIM7jQpUkf9HXcLZe5CFuxtuNxNqXoEdIGf7gOw6O0/zrxA+zG7mh0y1GPR9+00z9yPa5PBTna235p7FGBhR9DoOZiF7PDvvT4ZgVL2Cin+3xZ1I5cmCIZzxjg8a8Qi33zCbO0WAMlAckRzQJdnyF7JIU/WYGZdG55bQekGR08Ddoc7nX3tfQ2H211gT8TTm2HFijohroU9uNo2MoK0cwbe+IwkNtARyIBs7VtcW2+CKb/+L4Nbu4FqwgLdcv+CkeTndWQ2wExCw7d9x+6dL+wTaDb9stF5GqNDmC8VvIaX0ZKy9NquODO4vBAy07bjv3/vlyewOs/q0rHSUdwbfHsHeaBKUBxMeFo9QxT2hSCMgE1VJqkVv/qeYEpyqfujgZzmWo5Bsdmfs6tICnWryTlYHAXrKpMQz9Rt+9/FSwHQ961hPRg51linMb25ySGx4Sc/yKyECh1BOWuonm7e3YBFGF9yy9fvkEiOtszVPPwlcjwZ0+hKXCdve3TiZ0JuoemBxiyFEtk37T1j5KXvsYwOEv8hAgo2Xj17mYkUxlwbem6CYpnFwBgzj2FuYq
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull
      namespace: quizup-prod
    type: kubernetes.io/dockerconfigjson
