---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-infra-secret
  namespace: quizup-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB5D0nvvSfEmQoMoayFYc5UuUQwVle2VeUd9BOnLzkYQtEL0MYyyYxDQVF8ulhV5xlS5JNw1ShARd2L8O6G3ojEcCY72kTszljU0X8j6qGAX5xCFB+7vO10FG15xALnX+CjOcz1Ce1kJFctHAKMDVYpanmY3gTA2bZnocdp/OHQSroqrU3JPs4H8xE0Ov8b+3ZwPPedA/nDOJkKfvB2NDolGpl2MCGwenC/5nJ+OvbdFgzkhbC3SiD61ygJfH5tKcIkwu/ebL2xSkdUY2vZqDdvvTDERYKlKsqAwvH1vDhlpwRj4JDCkePJcKc9ov+/Ggnu4EmLibYcstdROTEHaZKotIAt1urqyAX+0hpZfNWWXrrtn/L3Q21yuf+3yl1gcweTdqPRIswrVBPbAOevqRMfEKvAm/PmlyKku7vEzngfrIbHc6GsqxWORvPkNQ1a8m2qBgdzGYjbs5doD9MXHEAlLxi1c+Lw9q5gI2vfqvnEnJ/oHVTGQ/m2YUaAigBYELbQzJJ2R+mBiVFwEoa4+bGiD2MncrvQR1LpsAXBIY74HeSLvcCWbal3tzee8qohwlo9phyROyKkmfHqg/cR0Gd7NsicYk93oFbKtGEs1rxjmn//3NZYvlfqCgLPUugSwA3wb2Y78Zu2rO5vDOZ/Ro/8x2BMaIzwt5AEYPVaewMWa5OVmoqLmDKAf1bQQAUMvrlqjvKRRQqR6z7mM3S2wG0DOPoZS85U89TjdekEEOMw/Zr7IqKhEV/mD73OrmbrbtE=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-infra-secret
      namespace: quizup-prod
