---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-theme-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_PASSWORD: AgCQVxNltsT3IJvm0EaedneJES3rUI5akQW9SOVqsLVdRTgystiJn1YG5f0sayrHKm8zwFHfWczHqqE0BX+O0L4MtXtg+l5qA7zysR7T2BzVIaNr9M3zKGSIZNWQN5LWhX/nUUVlCO/1kwPd76UmoZpYq+Ombnq9mkETikCZ+HPRxZ7C1X++1b5BzN345RBrDNWx5zAZggUZHWKYHVHhpvTCr+RaVZuKwZJgkVZ6BUBv24wVjI/jUm2r1mhT9Yb0sg2yWFXn8Rhscz1RovFsDa3wy+cgfTytMl1iiASqYRVsXH2OK2+/+poqcdqCFk1RvfD3m/XCD1nUDzQr8LXNJkVQn1Y7L2wkrcuY40URhVRPLKM0pgkd/dJWLnWSH6SWGwUAeLojaSq5IElYXAHJFEGwnrD8+HGloWlr4sMzLYCXree18WQ+FZSS0DQkmC6Hn0U13YHRDe8teJdUt1y22u4aTcUn7RxWeYwhDNKp+e04jWqs8/rV3Z7vMPjRW/YRxREGjtUbusvD9LzJoXCX4SJBE3cTP/IvuXWkYJ+e8M0WCsg4/jdHRxKoCWAWZDPruAKgvyK/ptJxcFaiLpf3Cuc8hp3PgoN4Gn+jyS+daMiV4zq7GfTaTqattt2qNXUizs6o7Q64oBaFSzT6e9aVGdRFelK0LkRtO0I3xlbZ0dkm6niJ56Gjcq8g3BSp2IvcItxUmPH5krCay3NigYsi1Z43cuGWgSJuOjZKR6mRVfmGBmTqWA46dvgszIeiw+uIBpA=
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgAO8p3pT1DEoERL1djEjkLpaDKD7VKdwHOkkYUxxEJ3alNC2Qx5382uNW/Ha3dYiuxAlq4lAlT4jcVYcyqIXFXDXav47rwJ/ovu/IYvYWtOtBW6Set9p3TTU2zfMhY51bwF+gNr/f3aepLJ5a2YHfUgafXF9+GzZA1MVIxPKvY5HXLmotbnR7MP/39d7YX0sMbTbRUEsncorhDuBDakVSLhqZ5iBd5JHZEvJNszlDhJqDqspSGly+n+lfKNe/L7omqyznFZNCY3s2Rw0arOBtMYlpxLGM6OJjcEom0Nkb2SZn6ZOSoR/U71rSYeiNPz+B2jrQHETHOZBY5Nxm4aHEp5/eXZWMFyQgxXHwJCtje7Azk4ve0wRNyEvSS3EHVJI08ilWCW1g7RKDvFjUcJ/O3AQ1QOlTYq1aB5rkKibFkA2pGBxvM0afUOfWDIHvSKRiOtsupVIg3kWg6PcOXfWZY+gCTX3UfFvhC4n0WzuNk/wgD8NaYwyR7JB5/FLGM+z6dVA7Ck4fdl4dMV0f22jKApnrLe3fXPWOqn9I7ICXduIPAvhPM3NtkPeCZ1OVkjLLN7Tjpf+yoMoI6RlNkwmX2ts7FPK4RUPXqZpKsjpSiOJPNuEPVdOvdBpsMRzzdKZUN/p+jbEMMUxHlxyWi64Rnzq2kvGumae2EUIm8S/DvA7NGR/kAhh259LGUOD49O8uowbMm4uCUS7c9ypr8QP9GDFADL7AnS2Ugb0Ch1oMZGTL4vU2VqSO6InYg7TniSiuU=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-theme-secret
      namespace: quizup-prod
