---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quizup-theme-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_PASSWORD: AgAxv6kAxRLuul5FPXqpetUVeLvg4qrUQMVwLoCnYrzp3wv5E6iIdbN1gVx5D6dcVGLWejWJrn7oaI5DMtB9zlNX3BEfld3Qe0sYoAY8OJouwEzwVTOd3NACAb33oaQJ0DhgszwJ7vFMhi7MWem+8k/NRa8xY112bD3T1f1bS/LgPdh97R7CiVc9k+sVqU9hWspN74Rhpy2MG75Hjwmeaq8bC0AiAgA8zX9nXNmEWeBPy2mmiTYekhLPDzcQgl4n0CKwAKgy+hyIFaDqN0AcxmvgOh7iw42o+C2FOdoPq+Q9HCzNwoWYZYm7JJOj3O0hnmX6uVyAtl7OCQhD4AzztsR6PLhHPHaI/PrAkNEVToTSQVTmsk+Qg1/oYtsqDCF7ahqdYFcoOoLJ6UUu1DgbtqbzZX2WtjrhmnH79F1NV0DkvRq3vLdnR8uI/ckJidtKGqqRjyeEYccFymXAIZrKwwi/4KxwOn1lp70rUr0UspEo6wkFvE98O4jydGDRqDssFkl5OgsLPiChlREZm7RziXATUyYisiY8I7CA9Dnvk54j97JLZCu8OgOUG28g7QV8ZKjMnA/Ri4jVsy/T5c6W0pZAK87T9H42mWXrWUbzVyJ/lk+6YLKK39B/T3+wHDoCvwgwnssa+rvtj9//2LKoBwO1cBsKAN4162gXU+doIIkyv73EClvw9mxWHGgquJSpbr4gsqLeMTTP8YSJI8j18KlkK0WZq1OhjTFf9cLd+cyf8TUJNACQQ7+GsfsJ+JxF7hQ=
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SERVER_CLIENT_CLIENT_SECRET: AgAGRAdkhI5k4EK4Fv+xc7a0kEUwRHouxTqQAfvCU+0vK2ij6r3MsJ0yXJNSlEkdZsHh3ld6hz6CKN9k24nID/PDnT0QsCqTcKJjrDQd92FLg47tokJgUJGssA5FVmYvFZn3SEhfLn0zIV9m77GLFp+/6WtWPB20Ykosnfh253Ns0Q+XcYCjbBcTEqOybjw73C8InMD8rbzq/HY8dNYEFLh4ZMSBG9dXiYRhGt/WNH9WRmj4jEF8l5/NeyepV13ztq/OBXqgay2Vm6jw6U+K693fq/uD8mwXefp2ZZmYE+NzX4iOpWgi4we6UsGRr3YwZCxfxO+xTMp3wZJg94b9NMWWI5ifKS2WcCA2BReIoqzVD+u7iRDY+aTkI9PHbHC6Y5mxm8jXSGIaVx++o4C6Z5BRrpag+QnZuRqXKoYsmqUir89idNAL+liAkcT/Gn/RPjIzG0eggXzoip4EPVzAopTGk7qnAPO05r90S09AeddVty8Aak/FwkscKKZ/mXvVtNg63nhMzZam7tGcDA63OfNO1zMAHic3pCwfxYPMlA688NVyxrZEOdUjr4mMsa8zo7l7PfiePy1Qqf5N1qUUR6aRvIHn8X6vhYlTLUeU3dRFMBY/bNoikpuu106QBTzbVD19M0N0UzzZnXJmnFcLa7Os/+OhCqa/9lNljlP5s4Kw6pk/qzsvCgACeaXxDAc2avWFKwxDwRLNIfBFiO9sXuiagQCq4FqODzVHABA6DChMb861GGGgCLDy3neERYqD/+w=
  template:
    metadata:
      creationTimestamp: null
      name: quizup-theme-secret
      namespace: quizup-prod
